codefordenver/ideaLab

Backend/src/main/java/idealab/IdeaLabMain.java, Backend/src/main/java/idealab/api/controller/PrintJobController.java, Backend/src/main/java/idealab/api/model/CustomerInfo.java, Backend/src/main/java/idealab/api/operations/PrintJobOperations.java, Backend/src/main/java/idealab/api/schedule/DeleteUserInfoCronJob.java, Backend/src/main/java/idealab/api/util/DeleteUserInfoCronJob.java, Backend/src/main/resources/import.sql, Backend/src/test/java/idealab/api/controller/PrintJobControllerTest.java, Backend/src/test/java/idealab/api/operations/PrintJobOperationsTest.java, Backend/src/test/java/idealab/api/schedule/DeleteUserInfoCronJobTest.java
30 Days clean up of customer info
=> Delete Customer Info Cron Job

Backend/src/main/java/idealab/api/controller/PrintJobController.java, Backend/src/main/java/idealab/api/dto/response/GetPrintJobResponse.java, Backend/src/main/java/idealab/api/operations/PrintJobOperations.java, Backend/src/test/java/idealab/api/controller/PrintJobControllerTest.java, Backend/src/test/java/idealab/api/operations/PrintJobOperationsTest.java
Updated the get all print job endpoint to use the PrintJob model directly.
=> 31 print job endpoint

Backend/src/main/java/idealab/api/controller/PrintJobController.java, Backend/src/test/java/idealab/api/controller/PrintJobControllerTest.java
changed endpoint naming to kebab case in PrintJobController and also adjustmented the unit-tests
=> changed endpoint naming to kebab case

src/components/BasicInput.jsx
I don't know how I missed adding that in.
=> fix BasicInput.jsx not being committed

.storybook/addons.js, .storybook/config.js, package-lock.json, package.json, src/components/MultiDropdown/Dropdown.css, src/components/MultiDropdown/Dropdown.js, src/components/MultiDropdown/Dropdown.stories.js, src/components/MultiDropdown/DropdownItem.jsx, src/components/MultiDropdown/Menu.jsx
This is just a start of a couple things. Not used anywhere in app at the moment, but it introduces storybook, which I think will be useful if we are building out individual components that will be meant to be reused.
Since the package files have been modified, remember to `npm install` and then run `npm run storybook` to see the component.
=> Multi dropdown component

.eslintignore, .eslintrc.js, .prettierrc.js, package-lock.json, package.json, src/SidebarNavigation.jsx
This closes #67 
I added in basic eslint rules from the Comrad/org projects, you are free to adjust/tweak as necessary for this project.
I also added in husky and lint-staged for any new files that get commited, you may also want to the ```prettier:all``` script at some point, but the rest of the team needs to get setup so there aren't a lot of merge conflicts.
=> Added basic eslint configuration

Backend/src/main/java/idealab/api/security/WebSecurity.java, Backend/src/main/resources/application.properties, Backend/src/main/resources/import.sql, src/App.js, src/AuthContext.js, src/SidebarNavigation.jsx, src/components/BasicInput.jsx, src/components/Login/LoginManager.jsx, src/components/Routing/PrivateRoute.jsx, src/components/Upload/UploadContainer.jsx, src/util/RequestService.js
closes #152 
Notes: 
Not 100% happy with how it looks right now in terms of the "shape" of how the context stuff is in relation to the request service, but I think it's more useful to get it in now in order to keep the feedback loop tighter and put us in a position to kind of break out some of the other issues into more digestible pieces since I expect there will be a few front end people working tonight.
It will probably be refactored based on style things and going back and finding out one thing or another doesn't work the way we want it to.
=> 152 add auth state handling to frontend

Backend/src/main/java/idealab/api/controller/UserController.java, Backend/src/main/java/idealab/api/dto/request/UserChangePasswordRequest.java, Backend/src/main/java/idealab/api/exception/ApiExceptionHandler.java, Backend/src/main/java/idealab/api/exception/ErrorType.java, Backend/src/main/java/idealab/api/exception/IdeaLabApiException.java, Backend/src/main/java/idealab/api/operations/UserOperations.java, Backend/src/main/java/idealab/api/security/SecurityConstants.java, Backend/src/main/java/idealab/api/security/WebSecurity.java, Backend/src/main/java/idealab/configurations/DropboxConfiguration.java, Backend/src/test/java/idealab/api/operations/UserOperationsTest.java
=> Change password

Backend/src/main/java/idealab/api/controller/PrintJobController.java, Backend/src/main/java/idealab/api/dto/request/GenericRequest.java, Backend/src/main/java/idealab/api/dto/request/PrintJobDeleteRequest.java, Backend/src/main/java/idealab/api/dto/request/PrintJobNewRequest.java, Backend/src/main/java/idealab/api/dto/request/PrintJobUpdateRequest.java, Backend/src/main/java/idealab/api/dto/request/PrintModelUpdateRequest.java, Backend/src/main/java/idealab/api/dto/request/UserChangePasswordRequest.java, Backend/src/main/java/idealab/api/operations/DropboxOperations.java, Backend/src/main/java/idealab/api/operations/PrintJobOperations.java, Backend/src/main/java/idealab/api/operations/UserOperations.java, Backend/src/test/java/idealab/api/operations/PrintJobOperationsTest.java
=> Validate requests

src/SidebarNavigation.jsx
Front end is looking great!
I just did a minor change to the sidebar so that the links show/hide based on if someone is logged in.
=> Updated the nav to hide all the inactive links until someone is logged in

README.md
Added some documentation for the frontend portion of the readme file
=> Add frontend doc

Frontend/src/components/Queue/QueueContainer.jsx, Frontend/src/components/Queue/components/PrintCardContainer.jsx, Frontend/src/components/Queue/components/Queue.jsx, Frontend/src/components/Queue/components/components/PrintDateAdded.jsx, Frontend/src/components/globalStyles/MenuTabs.js, Frontend/src/util/RequestService.js
=> 125 wire up queue page to print jobs endpoint

Backend/src/main/resources/import.sql
Hi @jberns this PR includes the new columns in inserts from import.sql file
=> Adjustments in import.sql to insert new columns #188

Backend/src/main/java/idealab/api/controller/PrintJobController.java, Backend/src/main/java/idealab/api/operations/PrintJobOperations.java, Backend/src/main/java/idealab/api/repositories/PrintJobRepo.java, Backend/src/test/java/idealab/api/controller/PrintJobControllerTest.java, Backend/src/test/java/idealab/api/operations/PrintJobOperationsTest.java
I removed the comment TODO and did as requested
=> Implementing find all print jobs by status #31

Backend/src/main/java/idealab/api/operations/UserOperations.java, Backend/src/test/java/idealab/api/controller/UserControllerTest.java, Backend/src/test/java/idealab/api/operations/UserOperationsTest.java
A simple solution to verify if user already exists
=> Validation if user already exists #138

Backend/src/main/java/idealab/api/controller/DropBoxController.java, Backend/src/main/java/idealab/api/controller/DropboxController.java, Backend/src/main/java/idealab/api/dto/request/DropBoxFilePathRequest.java, Backend/src/main/java/idealab/api/operations/DropboxOperations.java, Backend/src/main/java/idealab/api/operations/PrintJobOperations.java, Backend/src/test/java/idealab/api/operations/PrintJobOperationsTest.java
=> 162 rename

Backend/src/main/java/idealab/api/controller/PrintJobController.java, Backend/src/main/java/idealab/api/dto/request/UpdatePrintJobPropertiesRequest.java, Backend/src/main/java/idealab/api/operations/PrintJobOperations.java, Backend/src/test/java/idealab/api/operations/PrintJobOperationsTest.java
=> Update print job props

Backend/src/main/java/idealab/api/controller/PrintJobController.java, Backend/src/main/java/idealab/api/operations/PrintJobOperations.java, Backend/src/test/java/idealab/api/operations/PrintJobOperationsTest.java
This is a basic get mapping to return a single print job by its id.
=> Get one print job by

Frontend/src/components/Queue/QueueContainer.jsx, Frontend/src/components/Queue/components/Queue.jsx, Frontend/src/components/globalStyles/Loader.css, Frontend/src/components/globalStyles/Loader.jsx
=> add loading indicator to Queue page

Frontend/src/components/Queue/QueueContainer.jsx, Frontend/src/components/Queue/components/PrintCardContainer.jsx
This adds the current dropbox filepath name and link to the print card.
=> Added dropbox info to queue cards

Backend/src/main/java/idealab/api/dto/request/GenericRequest.java, Backend/src/main/java/idealab/api/operations/PrintJobOperations.java, Backend/src/test/java/idealab/api/operations/PrintJobOperationsTest.java
Signed-off-by: Piyush Mor <piyush.mor@gmail.com>
=> Clean-up the Code

Backend/src/main/java/idealab/api/operations/DropboxOperations.java
Signed-off-by: Piyush Mor <piyush.mor@gmail.com>
Fixes #203
=> changes from copy and del to move. Renames to .stl

Frontend/src/App.js, Frontend/src/components/Login/LoginManager.jsx
Related to:
https://github.com/codefordenver/ideaLab/pull/218
Fixes a weird bug where the token didn't get set because of an extra render, I believe.
=> 181 extra rendering issue fix

src/App.css, src/components/Upload/components/Upload.jsx
related to #148 
I think the other parts of #148 should be a backend responsibility if we are not doing the thing where we spike the upload url.
=> add filesize validation to front end

README.md
=> Updated readme for docker-compose documentation

Backend/src/main/java/idealab/api/controller/PrintJobController.java, Backend/src/main/java/idealab/api/operations/PrintJobOperations.java
Can one of you validate my assumptions and approve / merge if I'm correct on it? 
My understanding of what's going on in the code that I changed is that line 252 of PrintJobOperations.java is doing the same thing as line 87 in the PrintJobOperations.java
And that assumption is partially based on the comment:
>    //Don't include the field in the JSON if you dont want it updated
So ideally, a payload like`{"colorType":"green"}` should be a valid payload to update the color.
=> fix employee not being found by using spring's Principal

README.md
Hello, 
I am a new member of Code for Denver and I was checking out your project. This is a cool project and I love that it will people in the community get into 3D printing.
Kind Regards,
Patrick Candlin
=> Fixed minor typos

Frontend/src/components/Queue/components/PrintCardContainer.css
=> Added a border

Backend/src/main/java/idealab/api/model/ColorType.java, Backend/src/main/java/idealab/api/model/PrintJob.java, Backend/src/main/java/idealab/api/model/Queue.java, Backend/src/main/java/idealab/api/operations/PrintJobOperations.java, Backend/src/test/java/idealab/api/controller/PrintJobControllerTest.java, Backend/src/test/java/idealab/api/operations/PrintJobOperationsTest.java
=> Removing id from foreign keys in java

Frontend/src/components/Queue/QueueContainer.jsx
=> fix issue #256 by accessing the correct value

Frontend/src/components/AdminSettings/AdminContainer.jsx, Frontend/src/components/AdminSettings/AdminSettings.css
Added ideaLab logo to AdminContainer and added margins to container's status menu.
=> 252 adminlogo

Frontend/src/components/Queue/QueueContainer.css, Frontend/src/components/Queue/components/PrintCardContainer.css
=> Fix css issues for queue

Frontend/src/App.js
=> fix lack of redirect to queue page

Frontend/src/App.css
Fixed issue by adding input::placeholder values to App.css. Recommend styling as appropriate.
=> Invisible placeholder text fix

Backend/src/main/resources/import.sql
=> remove revinfo table insertions that were causing trouble

Backend/build.gradle, Backend/src/main/java/idealab/api/controller/MailController.java, Backend/src/main/java/idealab/api/dto/request/MailRequest.java, Backend/src/main/java/idealab/api/service/EmailService.java, Backend/src/main/java/idealab/api/service/EmailServiceImpl.java, Backend/src/main/java/idealab/configurations/WebMail.java, Backend/src/main/resources/application.properties
=> initial email setup with throwaway account

Backend/src/main/resources/import.sql
=> use correct sql comment syntax

Frontend/src/components/AdminSettings/components/ProfileInfo.jsx
=> Changed from alert to confirmation

Frontend/src/components/AdminSettings/UserProfilesContainer.jsx
This closes #292.
Fixed the formatted username so it displays properly in the table.
=> Updated username text field

Frontend/package.json, Frontend/src/components/AdminSettings/CreateAccountManager.jsx
Closes #139 
This does require a new dependency, react-toast-notifications
=> Toasts for user creation success/failure

Frontend/src/App.css, Frontend/src/components/Queue/QueueContainer.jsx, Frontend/src/components/Queue/components/ColorPickerContainer.jsx, Frontend/src/components/Queue/components/PrintCardContainer.css, Frontend/src/components/Queue/components/PrintCardContainer.jsx, Frontend/src/components/Upload/UploadContainer.css, Frontend/src/components/Upload/UploadContainer.jsx, Frontend/src/util/ColorUtils.js
This closes #246 .
Refactored the color picker and color getter into their own functions and then imported each into both the Queue and Upload components.
=> 246 upload color picker

Backend/src/main/java/idealab/api/controller/UserController.java, Backend/src/main/java/idealab/api/dto/request/EmployeeSignUpRequest.java, Backend/src/main/java/idealab/api/dto/request/EmployeeUpdateRequest.java, Backend/src/main/java/idealab/api/model/EmployeeRole.java, Backend/src/main/java/idealab/api/operations/UserOperations.java, Backend/src/test/java/idealab/api/controller/UserControllerTest.java, Backend/src/test/java/idealab/api/operations/UserOperationsTest.java, Frontend/src/components/AdminSettings/UserProfilesContainer.jsx, Frontend/src/components/AdminSettings/components/ProfileInfo.css, Frontend/src/components/AdminSettings/components/ProfileInfo.jsx, Frontend/src/util/RequestService.js
This closes #295 
Added basic request service for updating roles and then a confirmation text when it is successful.
=> Updated backend to accept role updates for employees

Backend/src/main/resources/import.sql, Frontend/package-lock.json, Frontend/src/App.css, Frontend/src/App.js, Frontend/src/components/AdminSettings/AdminSettings.jsx, Frontend/src/components/AdminSettings/CreateAccountManager.jsx, Frontend/src/components/AdminSettings/components/ChangePasswordModal/ChangePasswordModal.css, Frontend/src/components/AdminSettings/components/EmailMessage.css, Frontend/src/components/AdminSettings/components/EmailMessage.jsx, Frontend/src/components/AdminSettings/components/ProfileInfo.jsx, Frontend/src/components/Queue/QueueContainer.jsx, Frontend/src/components/Queue/components/PrintCardContainer.jsx, Frontend/src/components/Queue/components/SendEmailModal.jsx, Frontend/src/components/globalStyles/Backdrop/Backdrop.jsx, Frontend/src/util/RequestService.js
closes #310 
Test email sending. I did this by changing the first person in import.sql (in backend -> resources) email to your own and then changing it to the "FAILED" print status.
Also I know it is ugly. I'm going over everything with Patrick at the end to figure out what needs to change design wise. I decided to not worry about it now and wait until then.
=> 310 email stuff

Backend/src/main/java/idealab/api/security/SecurityConstants.java, Backend/src/main/java/idealab/api/security/WebSecurity.java
=> Updated security for all sites

Frontend/src/App.css
=> Css global issue

Frontend/src/components/AdminSettings/AdminSettings.css, Frontend/src/components/AdminSettings/UserProfileContainer.css, Frontend/src/components/AdminSettings/components/EmailMessage.css, Frontend/src/components/AdminSettings/components/EmailMessage.jsx, Frontend/src/components/AdminSettings/components/ProfileInfo.css, Frontend/src/components/AdminSettings/components/ProfileInfo.jsx, Frontend/src/components/AdminSettings/components/UpdateEmail.jsx
fixes to email settings section, save buttons, and password buttons styling and content
=> manage accounts css fixes

Frontend/src/components/Queue/components/ColorPickerContainer.css, Frontend/src/components/Queue/components/ColorPickerContainer.jsx, Frontend/src/components/Upload/UploadContainer.css, Frontend/src/components/Upload/UploadContainer.jsx, Frontend/src/components/Upload/components/Upload.jsx, Frontend/src/components/globalStyles/BasicInput.css, Frontend/src/components/globalStyles/CommentsInput.jsx
=> 328 css upload page

License.md
Adding an MIT license to the project.
=> Add a license file
